defaults: &defaults
  DB_USERNAME: root
  DB_PASSWORD: 
  DB_SOCKET: /var/run/mysqld/mysqld.sock
  SLACK_API_TOKEN: xoxp-
  SLACK_CLIENT_ID: "00000000000.00000000000"
  SLACK_SECRET: aaaaaaaaaaaa000aaaaaaaaaa
  SLACK_URL: https://
  SLACK_ON_RAILS_TOKEN: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  ROOT_PATH: ""
  SLACK_ON_RAILS_IMAGE_ROOT_PATH: "/images"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
