defaults: &defaults
  DB_USERNAME:
  DB_PASSWORD:
  DB_SOCKET: /var/run/mysqld/mysqld.sock
  SLACK_API_TOKEN:
  SLACK_CLIENT_ID:
  SLACK_SECRET:
  SLACK_URL:
  SLACK_ON_RAILS_TOKEN:
  ROOT_PATH: "slackonrails/"
  SLACK_ON_RAILS_IMAGE_ROOT_PATH: "/images"
  SLACK_TEAM_NAME: "TEAMNAME"
  SLACK_TEAM_ID: "T00000L"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  SECRET_KEY_BASE:
